### ISSUE TITLE
'network_from_json' is not defined

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/gnpy#10]
running ```python3 -m core``` from the root directory of proposal_network_architecture generates a name error:
```$ python -m core
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/github/gnpy/core/__main__.py", line 117, in <module>
    exit(main(args))
  File "/projects/github/gnpy/core/__main__.py", line 38, in main
    network = network_from_json(json_data)
NameError: name 'network_from_json' is not defined
```

**Comment by briantaylor89** [comment]
Please record an issue in Github.

Thanks


Sent from my iPhone

On Nov 28, 2017, at 10:09 AM, Gert Grammel <notifications@github.com<mailto:notifications@github.com>> wrote:


running python3 -m core from the root directory of proposal_network_architecture generates a name error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/github/gnpy/core/__main__.py", line 117, in <module>
    exit(main(args))
  File "/projects/github/gnpy/core/__main__.py", line 38, in main
    network = network_from_json(json_data)
NameError: name 'network_from_json' is not defined

**Comment by ggrammel** [comment]
Brian,

the email you responded to was sent by github, because that’s where I reported it in the first place.

Gert

Sent from my iPhone

On 30. Nov 2017, at 02:44, Brian Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


Please record an issue in Github.

Thanks


Sent from my iPhone

On Nov 28, 2017, at 10:09 AM, Gert Grammel <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


running python3 -m core from the root directory of proposal_network_architecture generates a name error:

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/projects/github/gnpy/core/__main__.py", line 117, in <module>
exit(main(args))
File "/projects/github/gnpy/core/__main__.py", line 38, in main
network = network_from_json(json_data)
NameError: name 'network_from_json' is not defined
