### ISSUE TITLE
testing installation: error

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/gnpy#53]
running through installation as described in Readme on 2018-04-16 on my Mac:

pip3 install gnpy --> works

Traceback (most recent call last):
ggrammel-mbp:gnpy ggrammel$ python examples/transmission_main_example.py 
  File "examples/transmission_main_example.py", line 106, in <module>
    exit(main(args))
  File "examples/transmission_main_example.py", line 41, in main
    network = network_from_json(json_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 29, in network_from_json
    g.add_node(getattr(elements, el_config['type'])(el_config))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/elements.py", line 111, in __init__
    self.dispersion = self.params.dispersion  #s/m/m
AttributeError: 'ConfigStruct' object has no attribute 'dispersion'

**Comment by ggrammel** [comment]
Checking the timestamps of files and folders and conclude those were not in sync with the timestamps on current master. So this appears to be an error caused by an installation or configuration issue. probably something in the Radme is missing.

**Comment by ggrammel** [comment]
Procedure doesn't seem to work if an older GNPY repository is lingering on the same computer. README may be misleading.

1) does `pip install gnpy` install also /gnpy/examples?
2) if so, where?
3) if not, README is misleading as it suggests examples could be run by simply installing gnpy
