### ISSUE TITLE
testing gnpy with coronet example 

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/gnpy#54]
2018-04-16 successfully installing GNPY followingthe readme
Trying using GNPY with the Coronet example as described in our Readme:

execution was from the GNPY directory:
```

> ggrammel-mbp:gnpy

ls
README.rst		examples		setup.py
contributors.md		gnpy
docs			requirements.txt

```

```
ggrammel-mbp:gnpy ggrammel$ python examples/transmission_main_example.py examples/coronet_conus_example.json
Traceback (most recent call last):
  File "examples/transmission_main_example.py", line 106, in <module>
    exit(main(args))
  File "examples/transmission_main_example.py", line 38, in main
    with open(args.filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/coronet_conus_example.json'

```

I then checked for the presence of this file and realized the name probably changed to
`examples/coronet.conus.json`

now trying with 

```
ggrammel-mbp:gnpy ggrammel$ python examples/transmission_main_example.py examples/coronet.conus.json
Traceback (most recent call last):
  File "examples/transmission_main_example.py", line 106, in <module>
    exit(main(args))
  File "examples/transmission_main_example.py", line 41, in main
    network = network_from_json(json_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/network.py", line 29, in network_from_json
    g.add_node(getattr(elements, el_config['type'])(el_config))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gnpy/core/elements.py", line 107, in __init__
    self.length = self.params.length * \
AttributeError: 'Fiber' object has no attribute 'params'
```
is the Readme to be updated or is our main branch broken?

**Comment by ggrammel** [comment]
the files in folder GNPY do not have the same date as the ones in Master. so likely an installation issue but what went wrong?

**Comment by ggrammel** [comment]
combination of a user error and a real issue in Master. Close this issue.
Issue of not executing example code in Master is tracked by #55
