### ISSUE TITLE
__main__.py: ImportError: cannot import name 'network_from_json'

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/gnpy#9]
Trying to run ```__main__.py``` from proposal_network_architecture but ends up with an error:
```
$ python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 15, in <module>
    from . import network_from_json
ImportError: cannot import name 'network_from_json'
```

**Comment by ggrammel** [comment]
Running ```python3 -m core``` from the root directory of repository proposal_network_architecture ends with a NameError: 
```$ python -m core
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/github/gnpy/core/__main__.py", line 117, in <module>
    exit(main(args))
  File "/projects/github/gnpy/core/__main__.py", line 38, in main
    network = network_from_json(json_data)
NameError: name 'network_from_json' is not defined
```

**Comment by ggrammel** [comment]
Was incorrect to run __main_ directly from core. Instead use ```python3 -m core``` from root directory of proposal_network_architecture.
